name: test actions
description: action
on: [push]
jobs:
  test-gh-actions:
    run-on: ubuntu-latest
    steps:
      - run: echo "testing"
      - name: checkout
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
       - name: List files in the repository
        run: |
          ls -r ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."